name: Deploy React App to GitHub Pages

on:
  push:
    branches: [main] # Deploy whenever you push to main

permissions:
  contents: write # Allow pushing to gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests (optional)
        run: npm test --if-present

      - name: Build the project
        run: npm run build

      - name: Configure Git identity
        run: |
          git config --global user.name "jahnavinnusum"
          git config --global user.email "jahnavinusum@gmail.com"

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          npm run deploy
